import { PublicAct, ReasoningRecord, User } from '@/types';
import { communities } from '@/lib/communities';

const weltform = communities.find((c) => c.slug === 'weltform')!;

export const weltformCompiler: User = {
  id: 'compiler-voss',
  username: 'elena_voss',
  name: 'Elena Voss',
  bio: 'Partner, Weltform. Tiene il registro del giudizio della partnership.',
  createdAt: new Date('2024-03-01'),
};

const demo = 'Fonte dimostrativa interna. Non è un documento reale.';

export const weltformActs: PublicAct[] = [
  {
    id: 'act-wf-pe-2026',
    title: 'Mandato rifiutato: non fare il file del fondo su Nordlux',
    actNumber: 'CRM-MND-2026-014',
    entity: weltform,
    date: new Date('2026-06-04'),
    rawTextExcerpt: `OGGETTO: gara Silverpeak su Nordlux (componentistica, Brescia)
DOMANDA: possiamo aiutare a tagliare l’organico come chiede il contratto di acquisizione?
DECISIONE: no. Non presentiamo offerta. Risposta scritta entro il 6/6.`,
    slug: 'weltform-rifiuto-mandato-pe-2026',
    createdAt: new Date('2026-06-05'),
    updatedAt: new Date('2026-06-05'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-pricing-2026',
    title: 'Prezzo 2026: vendiamo una risposta, non giornate che si allungano',
    actNumber: 'PRT-2026-09',
    entity: weltform,
    date: new Date('2026-05-12'),
    rawTextExcerpt: `PROBLEMA: i mandati strategia durano più del previsto; il cliente paga a giornata, noi paghiamo le settimane in più.
DECISIONE: i nuovi mandati si chiudono a fee fissa e tempo concordato. I contratti già firmati restano invariati.`,
    slug: 'weltform-pricing-fee-2026',
    createdAt: new Date('2026-05-13'),
    updatedAt: new Date('2026-05-13'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-ai-2026',
    title: 'Policy AI: fiducia del cliente prima della comodità dello strumento',
    actNumber: 'POL-IT-2026-03',
    entity: weltform,
    date: new Date('2026-03-20'),
    rawTextExcerpt: `FATTO: dati di un cliente retail finiti su un modello pubblico (marzo 2026).
DOMANDA: dove possiamo usare l’AI senza mettere in gioco ciò che ci hanno confidato?
DECISIONE: niente dati cliente su modelli pubblici. Solo trascrizioni interne su ambiente chiuso. Il lavoro che va al cliente resta umano.`,
    slug: 'weltform-policy-ai-2026',
    createdAt: new Date('2026-03-21'),
    updatedAt: new Date('2026-03-21'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-munich-2026',
    title: 'Germania: niente sede finché il mercato non la chiede davvero',
    actNumber: 'GEO-2026-01',
    entity: weltform,
    date: new Date('2026-01-22'),
    rawTextExcerpt: `PROPOSTA: ufficio a Monaco, contratto triennale, otto assunzioni locali.
SITUAZIONE: un mandato chiuso nel 2025, due gare perse; finora copriamo con voli da Milano.
DECISIONE: non firmare. Riaprire solo se due clienti tedeschi ci rinnovano fiducia nello stesso anno.`,
    slug: 'weltform-no-sede-monaco-2026',
    createdAt: new Date('2026-01-23'),
    updatedAt: new Date('2026-01-23'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-lateral-2025',
    title: 'Partnership: crescita interna invece del laterale con il book “intoccabile”',
    actNumber: 'PRT-2025-21',
    entity: weltform,
    date: new Date('2025-11-18'),
    rawTextExcerpt: `CANDIDATO ESTERNO: grande book, ma la maggior parte su un cliente già in conflitto con un mandato vivo.
ALTERNATIVA INTERNA: principal con origination solida, già dentro la cultura dello studio.
DECISIONE: no al laterale. Promozione interna ad aprile 2026.`,
    slug: 'weltform-no-lateral-2025',
    createdAt: new Date('2025-11-19'),
    updatedAt: new Date('2025-11-19'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-product-2025',
    title: 'Stop Pulse: siamo consulenti, non una software house',
    actNumber: 'OFF-2025-07',
    entity: weltform,
    date: new Date('2025-09-09'),
    rawTextExcerpt: `SITUAZIONE: sei mesi di sviluppo, un pilota gratuito, nessuno disposto a pagare l’abbonamento.
DOMANDA: continuiamo a costruire prodotto o torniamo a vendere giudizio?
DECISIONE: chiudere Pulse. Il diagnostic resta la prima fase del mandato, non un SaaS.`,
    slug: 'weltform-stop-pulse-2025',
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2025-09-10'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-notes-2025',
    title: 'Come parliamo in pubblico: un saggio l’anno, non il caso cliente su HBR',
    actNumber: 'COM-2025-02',
    entity: weltform,
    date: new Date('2025-06-16'),
    rawTextExcerpt: `RICHIESTA: articolo su rivista prestigiosa con un caso anonimizzato — il cliente ha detto no.
ALTERNATIVA MARKETING: newsletter e PDF dietro form per raccogliere contatti.
DECISIONE: un testo breve all’anno, libero sul sito, senza trucchi da lead generation. HBR: no.`,
    slug: 'weltform-note-giudizio-2025',
    createdAt: new Date('2025-06-17'),
    updatedAt: new Date('2025-06-17'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-conflict-2025',
    title: 'Conflitto nel lusso: un mandato alla volta sullo stesso canale',
    actNumber: 'CNF-2025-04',
    entity: weltform,
    date: new Date('2025-03-11'),
    rawTextExcerpt: `SITUAZIONE: mandato A in corso su e-commerce DTC; arriva gara B, stesso canale, importo più alto.
VINCOLO: trentacinque persone, un open space, un unico canale di lavoro.
DECISIONE: decliniamo B. Teniamo la parola data ad A fino a fine luglio.`,
    slug: 'weltform-conflitto-lusso-2025',
    createdAt: new Date('2025-03-12'),
    updatedAt: new Date('2025-03-12'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-build-2024',
    title: 'No PMO: strategia sì, presidio permanente no',
    actNumber: 'PRT-2024-16',
    entity: weltform,
    date: new Date('2024-11-07'),
    rawTextExcerpt: `RICHIESTA: un anno di project management on-site in fabbrica — fee importante, ma non è il nostro mestiere.
ALTERNATIVA: mandare il cliente a un partner operativo che lo fa per professione.
DECISIONE: rifiutiamo il SOW. Restiamo sul pezzo strategia già chiuso.`,
    slug: 'weltform-no-implementation-2024',
    createdAt: new Date('2024-11-08'),
    updatedAt: new Date('2024-11-08'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
  {
    id: 'act-wf-equity-2024',
    title: 'Indipendenza: no al fondo che impone di crescere per obbligo',
    actNumber: 'PRT-X-2024-01',
    entity: weltform,
    date: new Date('2024-09-03'),
    rawTextExcerpt: `OFFERTA: capitale importante in cambio di quota rilevante e obbligo di assumere ogni anno, a prescindere dal lavoro.
SITUAZIONE: sette partner, cassa sufficiente, utile stabile.
DECISIONE: non firmare. Crescere solo quando il giudizio lo chiede, non quando lo impone un covenant.`,
    slug: 'weltform-no-pe-equity-2024',
    createdAt: new Date('2024-09-04'),
    updatedAt: new Date('2024-09-04'),
    recordsCount: 1,
    isVerified: true,
    dataStatus: 'demo',
    verificationNote: demo,
  },
];

export const weltformRecords: ReasoningRecord[] = [
  {
    id: 'record-wf-pe-2026',
    publicActId: 'act-wf-pe-2026',
    publicAct: weltformActs[0],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Mandati',
    upvotes: 44,
    realQuestion: 'Accettiamo un mandato il cui scopo implicito è tagliare centinaia di posti di lavoro, sapendo che non possiamo cambiare la domanda dopo la firma?',
    discardedOptions: [
      {
        id: 'opt-wf-pe-1',
        title: 'Presentare offerta piena e accettare il KPI sull’organico',
        reasonDiscarded: 'Il fondo ha già fissato l’obiettivo nel contratto di acquisizione. Non resterebbe spazio per riformulare la domanda una volta dentro.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-pe-2',
        title: 'Entrare con un diagnostic breve, senza KPI di headcount',
        reasonDiscarded: 'Il fondo lega il secondo mandato al primo. Sarebbe un ingresso di facciata, non un pezzo autonomo di giudizio.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'Non presentiamo offerta. Scriviamo al fondo che Weltform non firma mandati il cui successo si misura in tagli di organico imposti dall’esterno.',
    uncertaintyLevel: 'medio',
    uncertaintyExplanation: 'È un mandato grande e il rifiuto lascia un buco nel piano dell’anno. Due partner temono che, senza alternative pronte, si paghi il coraggio con mesi difficili.',
    mindChangingConditions: [
      'Il fondo toglie per iscritto ogni KPI sull’organico e chiede un mandato su scelte industriali vere — impianti, mix produttivo, make-or-buy.',
      'A fine anno manca lavoro equivalente e il rifiuto si rivela insostenibile per la cassa dello studio.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-pe-1',
        quote: 'Il taglio è già nel contratto di acquisizione. Noi non siamo qui per eseguire il file del fondo.',
        pageOrParagraph: 'CRM-MND-2026-014, nota Voss',
        speaker: 'Elena Voss',
      },
    ],
    interpretativeSummary: 'Hanno rifiutato un mandato redditizio perché confondeva consulenza con esecuzione di una scelta già presa altrove. La fee non giustifica un mestiere che non vogliono fare.',
    outcomeReviews: [
      {
        id: 'out-wf-pe-1',
        timeframe: '12_mesi',
        expectedOutcome: 'Nessun mandato Silverpeak/Nordlux; il buco coperto da altro lavoro industriale.',
        status: 'pending',
        notes: 'Verifica a giugno 2027.',
      },
    ],
    createdAt: new Date('2026-06-06'),
    updatedAt: new Date('2026-06-06'),
  },
  {
    id: 'record-wf-pricing-2026',
    publicActId: 'act-wf-pricing-2026',
    publicAct: weltformActs[1],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Offerta',
    upvotes: 31,
    realQuestion: 'Continuiamo a vendere giornate — che si allungano — o una risposta a tempo e prezzo concordati?',
    discardedOptions: [
      {
        id: 'opt-wf-pr-1',
        title: 'Tenere il prezzo a giornata e alzarlo',
        reasonDiscarded: 'Il problema non è la tariffa bassa: è che i mandati durano più del previsto e il cliente non paga le settimane extra. Alzare il listino non cambia la dinamica.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-pr-2',
        title: 'Legare parte della fee al risultato economico del cliente',
        reasonDiscarded: 'Non controlliamo i numeri dopo il mandato. Chiedere un premio sul risultato sarebbe disonesto verso chi firma e verso noi stessi.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'I nuovi mandati strategia si chiudono a fee fissa e tempo concordato in offerta. L’overtime non si fattura: se sbagliamo la stima, lo paghiamo noi. I contratti già firmati restano invariati.',
    uncertaintyLevel: 'alto',
    uncertaintyExplanation: 'Alcuni clienti hanno ancora procurement che ragiona solo a giornata. Potremmo perdere gare solo per il formato, anche con un giudizio migliore.',
    mindChangingConditions: [
      'Entro un anno, troppe offerte perse per iscritto perché “manca il day rate”.',
      'Due mandati consecutivi sforano il tempo concordato senza che la domanda del cliente sia cambiata — segno che stiamo sottostimando il lavoro.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-pr-1',
        quote: 'Abbiamo fatturato settimane che non erano in offerta. Non è un premio: è un modo di lavorare che non vogliamo più.',
        pageOrParagraph: 'PRT-2026-09, riunione partnership',
        speaker: 'Luca Ferrante',
      },
    ],
    interpretativeSummary: 'Hanno scelto di vendere una risposta delimitata, non ore che scivolano. Il rischio commerciale è accettato in cambio di un mestiere più onesto.',
    outcomeReviews: [
      {
        id: 'out-wf-pr-1',
        timeframe: '6_mesi',
        expectedOutcome: 'Almeno metà dei nuovi mandati strategia a fee fissa; nessuna settimana extra fatturata.',
        status: 'pending',
      },
    ],
    createdAt: new Date('2026-05-14'),
    updatedAt: new Date('2026-05-14'),
  },
  {
    id: 'record-wf-ai-2026',
    publicActId: 'act-wf-ai-2026',
    publicAct: weltformActs[2],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Metodo',
    upvotes: 27,
    realQuestion: 'Dopo che dati di un cliente sono finiti su un modello pubblico, dove possiamo ancora usare l’AI senza tradire la fiducia?',
    discardedOptions: [
      {
        id: 'opt-wf-ai-1',
        title: 'Vietare ogni uso di AI, anche interno',
        reasonDiscarded: 'Trascrivere a mano ore di riunioni costa tempo che non abbiamo. Un divieto totale punisce il mestiere senza risolvere il problema vero: i dati del cliente.',
        evidenceType: 'interpretation',
      },
      {
        id: 'opt-wf-ai-2',
        title: 'Continuare a usare modelli pubblici con un disclaimer in calce',
        reasonDiscarded: 'Un disclaimer non cancella un NDA violato. La fiducia non si ripara con una riga in fondo alla slide.',
        evidenceType: 'verbatim',
      },
    ],
    decision: 'Niente dati cliente su modelli pubblici. Solo trascrizioni interne su ambiente chiuso. Deck, numeri e testi che vanno al cliente restano lavoro umano, controllato.',
    uncertaintyLevel: 'alto',
    uncertaintyExplanation: 'Non possiamo controllare il telefono personale. Senza conseguenze chiare, l’incidente può ripetersi per comodità, non per malizia.',
    mindChangingConditions: [
      'Un secondo incidente con dati cliente su strumenti pubblici entro un anno.',
      'Il cliente danneggiato recede dal rapporto per colpa dell’incidente.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-ai-1',
        quote: 'Non era una frase da riformulare. Era l’intero listino di un cliente sotto NDA.',
        pageOrParagraph: 'POL-IT-2026-03, verbale IT',
        speaker: 'Responsabile IT',
      },
    ],
    interpretativeSummary: 'La policy non nasce da paura dell’AI, ma da un fatto concreto. Hanno separato ciò che è interno e reversibile da ciò che è fiducia del cliente.',
    aiAssistance: {
      level: 'assistivo',
      scopes: ['transcription'],
      tools: 'Azure OpenAI (tenant chiuso, solo trascrizioni)',
      dataExposure: 'internal_only',
      note: 'Trascrizione del verbale IT su ambiente approvato. La scheda è stata scritta e validata dal partner; nessun dato cliente nel draft.',
    },
    outcomeReviews: [
      {
        id: 'out-wf-ai-1',
        timeframe: '6_mesi',
        expectedOutcome: 'Nessun nuovo incidente su modelli pubblici; rapporto col cliente retail salvo.',
        status: 'pending',
      },
    ],
    createdAt: new Date('2026-03-22'),
    updatedAt: new Date('2026-03-22'),
  },
  {
    id: 'record-wf-munich-2026',
    publicActId: 'act-wf-munich-2026',
    publicAct: weltformActs[3],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Geografie',
    upvotes: 18,
    realQuestion: 'Apriamo una sede in Germania con contratto triennale e assunzioni locali, quando il mercato ci ha dato una sola fiducia concreta l’anno scorso?',
    discardedOptions: [
      {
        id: 'opt-wf-mu-1',
        title: 'Firmare l’ufficio e assumere in loco',
        reasonDiscarded: 'Servirebbe un fatturato che non abbiamo. Il costo lo pagherebbe Milano, con il rischio di indebolire ciò che già funziona.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-mu-2',
        title: 'Prendere quattro scrivanie in coworking, senza assunzioni',
        reasonDiscarded: 'Non sblocca le gare che chiedono presenza vera. È un compromesso che non risolve né il problema né l’ambizione.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'Non firmare. Continuiamo a coprire la Germania con voli e presenza puntuale. Riapriamo la questione solo se due clienti tedeschi ci rinnovano fiducia nello stesso anno.',
    uncertaintyLevel: 'medio',
    uncertaintyExplanation: 'Alcune gare si perdono perché manca una sede locale. È un prezzo che accettiamo finché la domanda non diventa reale, non aspirazionale.',
    mindChangingConditions: [
      'Due clienti tedeschi ci affidano un secondo mandato nello stesso anno.',
      'Tre gare perse in dodici mesi con motivo scritto: assenza di presenza in Germania.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-mu-1',
        quote: 'Un ufficio triennale non è un segnale di ambizione. È un mandato che dobbiamo ancora guadagnarci.',
        pageOrParagraph: 'GEO-2026-01, riunione partnership',
        speaker: 'Elena Voss',
      },
    ],
    interpretativeSummary: 'Hanno rifiutato l’espansione simbolica. La sede deve seguire la fiducia del mercato, non precederla.',
    outcomeReviews: [
      {
        id: 'out-wf-mu-1',
        timeframe: '12_mesi',
        expectedOutcome: 'Nessuna sede in Germania; voli contenuti; riapertura solo se due clienti rinnovano fiducia.',
        status: 'pending',
      },
    ],
    createdAt: new Date('2026-01-24'),
    updatedAt: new Date('2026-01-24'),
  },
  {
    id: 'record-wf-lateral-2025',
    publicActId: 'act-wf-lateral-2025',
    publicAct: weltformActs[4],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Partnership',
    upvotes: 22,
    realQuestion: 'Assumiamo un partner esterno con un book impressionante ma in gran parte su un cliente che non possiamo toccare, o promuoviamo chi ha già costruito fiducia dentro lo studio?',
    discardedOptions: [
      {
        id: 'opt-wf-la-1',
        title: 'Accogliere il laterale con equity e draw elevato',
        reasonDiscarded: 'La maggior parte del book è su un OEM già in conflitto con un mandato vivo. Compliance ha detto no: non è un dettaglio negoziabile.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-la-2',
        title: 'Contratto esterno senza partnership, solo percentuale sulle origination',
        reasonDiscarded: 'Risolve la forma giuridica, non il conflitto. Stesso cliente intoccabile, stesso rischio per la reputazione.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'No al laterale. Promuoviamo internamente una principal che ha già portato lavoro credibile. Nessun budget per ingressi esterni nel 2026.',
    uncertaintyLevel: 'medio',
    uncertaintyExplanation: 'La promozione interna non porta un book pronto come quello del candidato esterno. Abbiamo scelto coerenza e crescita lenta rispetto a un colpo di volume.',
    mindChangingConditions: [
      'Entro diciotto mesi la promossa non origina abbastanza e non c’è nessun altro percorso interno credibile.',
      'Il fatturato strategia cala per due trimestri e compare un laterale senza conflitti di settore.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-la-1',
        quote: 'Un book su un cliente che non possiamo servire non è un asset. È un debito reputazionale.',
        pageOrParagraph: 'PRT-2025-21, parere compliance',
        speaker: 'General counsel interno',
      },
    ],
    interpretativeSummary: 'Hanno preferito chi conosce già il modo di giudicare dello studio a chi portava numeri che non potevano essere usati. Partnership è continuità, non solo fatturato.',
    outcomeReviews: [
      {
        id: 'out-wf-la-1',
        timeframe: '12_mesi',
        expectedOutcome: 'Neri in partnership ad aprile; nessun laterale; origination credibile nei primi dodici mesi.',
        actualOutcome: 'Neri partner dal 1/4/2026. Origination solida ma sotto le aspettative iniziali. Nessun laterale.',
        status: 'verified_true',
        reviewDate: new Date('2026-09-01'),
      },
    ],
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2026-12-15'),
  },
  {
    id: 'record-wf-product-2025',
    publicActId: 'act-wf-product-2025',
    publicAct: weltformActs[5],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Offerta',
    upvotes: 19,
    realQuestion: 'Continuiamo a costruire un prodotto software che nessuno vuole pagare, o torniamo a vendere giudizio come prima fase del mandato?',
    discardedOptions: [
      {
        id: 'opt-wf-pd-1',
        title: 'Finire il prodotto e venderlo in abbonamento',
        reasonDiscarded: 'Il pilota non ha pagato. Non c’è una coda di clienti disposti a sostenere un canone annuale. Continuare sarebbe speranza, non strategia.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-pd-2',
        title: 'Cedere il codice a una software house con il nostro brand',
        reasonDiscarded: 'Resterebbe il nome Weltform su qualcosa che non manuteniamo né controlliamo. Troppo rischio per troppo poco beneficio.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'Chiudere Pulse. Il diagnostic resta la prima fase del mandato — poche settimane, prezzo chiaro — non un SaaS separato.',
    uncertaintyLevel: 'basso',
    uncertaintyExplanation: 'I soldi già spesi non tornano. Il rischio residuo è solo morale: due persone volevano “finire” per principio.',
    mindChangingConditions: [
      'Tre richieste indipendenti, pagate, di diagnostic senza mandato successivo entro un anno.',
      'Un veicolo separato, senza brand Weltform e senza dati dei nostri clienti.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-pd-1',
        quote: 'Nessuno ha chiesto di pagare il cruscotto. Abbiamo costruito una risposta a una domanda che non ci avevano fatto.',
        pageOrParagraph: 'OFF-2025-07, riunione offerta',
        speaker: 'Partner offerta',
      },
    ],
    interpretativeSummary: 'Hanno chiuso Pulse non per ideologia anti-tech, ma perché il pilota ha detto chiaramente cosa vendiamo davvero: giudizio delimitato, non software ricorrente.',
    outcomeReviews: [
      {
        id: 'out-wf-pd-1',
        timeframe: '12_mesi',
        expectedOutcome: 'Zero ricavi da software; diagnostic solo dentro il mandato.',
        actualOutcome: 'Pulse non ripreso. Un cliente ha chiesto il cruscotto: rifiutato, riformulato come fase iniziale del mandato, firmato.',
        status: 'verified_true',
        reviewDate: new Date('2026-09-08'),
      },
    ],
    createdAt: new Date('2025-09-11'),
    updatedAt: new Date('2026-09-08'),
  },
  {
    id: 'record-wf-notes-2025',
    publicActId: 'act-wf-notes-2025',
    publicAct: weltformActs[6],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Metodo',
    upvotes: 16,
    realQuestion: 'Parliamo in pubblico del nostro lavoro — e come — senza tradire chi ci ha dato fiducia?',
    discardedOptions: [
      {
        id: 'opt-wf-no-1',
        title: 'Pubblicare un caso su rivista prestigiosa, anonimizzato',
        reasonDiscarded: 'Il cliente ha detto no, due volte. Non esiste “abbastanza anonimo” quando il canale e il settore sono riconoscibili.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-no-2',
        title: 'Newsletter frequente e PDF dietro form per raccogliere contatti',
        reasonDiscarded: 'Sarebbe marketing aggressivo, non pensiero. Trasformerebbe il giudizio in lead generation.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'Un saggio breve all’anno, libero sul sito, senza form e senza nomi. Doppia revisione dei partner. Niente HBR finché manca il consenso.',
    uncertaintyLevel: 'medio',
    uncertaintyExplanation: 'Un lettore attento potrebbe comunque indovinare. Accettiamo quel rischio minimo in cambio di un testo onesto e non strumentale.',
    mindChangingConditions: [
      'Reclamo scritto di un cliente che si riconosce nel testo.',
      'Il PDF viene usato come allegato commerciale o messo dietro form — segnale che il formato non regge.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-no-1',
        quote: 'La visibilità non vale una fiducia rotta. Se il cliente dice no, la risposta è no.',
        pageOrParagraph: 'COM-2025-02, mail legal',
        speaker: 'Legal',
      },
    ],
    interpretativeSummary: 'Hanno scelto pochi testi, liberi e non strumentali, invece della visibilità prestigiosa o del funnel commerciale. Parlare in pubblico è parte del mestiere, ma dopo la parola data.',
    aiAssistance: {
      level: 'sostanziale',
      scopes: ['drafting', 'summary'],
      tools: 'Claude (account studio, senza upload di file)',
      dataExposure: 'none',
      note: 'Prima bozza del saggio annuale; riscritta e approvata in partnership. Nessun caso cliente nel testo.',
    },
    outcomeReviews: [
      {
        id: 'out-wf-no-1',
        timeframe: '12_mesi',
        expectedOutcome: '1 PDF online; 0 reclami; 0 form.',
        actualOutcome: 'PDF aprile 2026, 11 pagine. Zero reclami. Due inbound da indirizzi corporate, non da form.',
        status: 'verified_true',
        reviewDate: new Date('2026-06-16'),
      },
    ],
    createdAt: new Date('2025-06-18'),
    updatedAt: new Date('2026-06-16'),
  },
  {
    id: 'record-wf-conflict-2025',
    publicActId: 'act-wf-conflict-2025',
    publicAct: weltformActs[7],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Mandati',
    upvotes: 36,
    realQuestion: 'Accettiamo un secondo mandato lusso sullo stesso canale e-commerce mentre il primo è ancora vivo, o teniamo una sola linea di giudizio per volta?',
    discardedOptions: [
      {
        id: 'opt-wf-cf-1',
        title: 'Due team separati nello stesso open space',
        reasonDiscarded: 'Trentacinque persone, un tavolo, un canale di lavoro. Il confine sarebbe teatro, non protezione. Non abbiamo neanche le persone per coprire entrambi.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-cf-2',
        title: 'Uscire dal primo mandato e prendere il secondo, più grande',
        reasonDiscarded: 'Il primo è a metà strada. Recedere ora brucia una relazione per un guadagno che non cancella il danno reputazionale.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'Decliniamo la seconda gara. Portiamo a termine il mandato A fino a luglio. Per un anno non accettiamo altro lusso sullo stesso canale.',
    uncertaintyLevel: 'basso',
    uncertaintyExplanation: 'Perdiamo un mandato grande e certo. Il calendario dell’anno regge comunque: abbiamo scelto coerenza prima del volume.',
    mindChangingConditions: [
      'Lo studio cresce abbastanza da avere team fisicamente separati e partner non sovrapposti sul lusso.',
      'La seconda gara cambia domanda — magazzino, non e-commerce — e la prima è già chiusa.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-cf-1',
        quote: 'Non abbiamo due stanze. Abbiamo un tavolo e una sola conversazione alla volta.',
        pageOrParagraph: 'CNF-2025-04',
        speaker: 'Luca Ferrante',
      },
    ],
    interpretativeSummary: 'Il rifiuto non è moralismo astratto: è limite reale di spazio e di attenzione. Hanno preferito finire bene un mandato a prenderne due incompatibili.',
    outcomeReviews: [
      {
        id: 'out-wf-cf-1',
        timeframe: '12_mesi',
        expectedOutcome: 'A chiuso 31/7; zero overlap lusso sullo stesso canale.',
        actualOutcome: 'A chiuso 28/7. B andata a un competitor. A ottobre mandato operations (non DTC) con terzo player, parere scritto di non overlap.',
        status: 'verified_true',
        reviewDate: new Date('2026-03-10'),
      },
    ],
    createdAt: new Date('2025-03-13'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: 'record-wf-build-2024',
    publicActId: 'act-wf-build-2024',
    publicAct: weltformActs[8],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Offerta',
    upvotes: 25,
    realQuestion: 'Accettiamo un anno di presidio operativo in fabbrica — redditizio ma non nostro — o restiamo nel pezzo di giudizio che sappiamo fare?',
    discardedOptions: [
      {
        id: 'opt-wf-bu-1',
        title: 'Firmare il mandato PMO e assumere una squadra operativa',
        reasonDiscarded: 'A regime perdiamo soldi e qualità. Il presidio permanente non è il nostro mestiere: lo faremmo male, lentamente, con overtime nascosto.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-bu-2',
        title: 'Subappaltare con co-brand Weltform sul badge',
        reasonDiscarded: 'Esporrebbe il nostro nome su una delivery che non controlliamo. Il cliente vedrebbe Weltform; la responsabilità sarebbe di altri.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'Rifiutiamo il PMO. Presentiamo un partner operativo che lo fa per professione. Restiamo sul mandato strategia già chiuso, fino a fine anno.',
    uncertaintyLevel: 'medio',
    uncertaintyExplanation: 'Il cliente potrebbe non rinnovarci lo strategy se interpreta l’assenza in fabbrica come distacco. È un rischio relazionale che accettiamo.',
    mindChangingConditions: [
      'Tre mandati strategia falliscono nell’adozione e il cliente dice per iscritto che mancava presidio operativo.',
      'Il partner usa il nostro brand sul sito del cliente — segnale che il referral non regge.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-bu-1',
        quote: 'Possiamo aiutare a decidere. Non possiamo presidiare un anno in fabbrica senza tradire chi siamo.',
        pageOrParagraph: 'PRT-2024-16, riunione offerta',
        speaker: 'Elena Voss',
      },
    ],
    interpretativeSummary: 'Hanno rifiutato fee facile per restare fedeli al mestiere. Il referral onesto vale più del co-brand su lavoro che non governiamo.',
    outcomeReviews: [
      {
        id: 'out-wf-bu-1',
        timeframe: '24_mesi',
        expectedOutcome: 'Nessuna squadra operativa assunta; partner senza co-brand; rinnovo strategy 2026 da tracciare.',
        status: 'pending',
        notes: 'Rinnovo 2026: da aggiornare a dicembre.',
      },
    ],
    createdAt: new Date('2024-11-09'),
    updatedAt: new Date('2024-11-09'),
  },
  {
    id: 'record-wf-equity-2024',
    publicActId: 'act-wf-equity-2024',
    publicAct: weltformActs[9],
    compiler: weltformCompiler,
    version: 1,
    status: 'published',
    category: 'Partnership',
    upvotes: 41,
    realQuestion: 'Scambiamo parte dell’indipendenza per capitale che ci obbliga a crescere per contratto, o restiamo piccoli e padroni del nostro giudizio?',
    discardedOptions: [
      {
        id: 'opt-wf-eq-1',
        title: 'Accettare il fondo con obbligo di assumere ogni anno',
        reasonDiscarded: 'Il covenant impone crescita dell’organico a prescindere dal lavoro. È l’opposto di come abbiamo rifiutato il mandato Harbor: giudizio sostituito da obbligo.',
        evidenceType: 'verbatim',
      },
      {
        id: 'opt-wf-eq-2',
        title: 'Prendere debito bancario per espandersi, senza cedere quota',
        reasonDiscarded: 'La rata annua mangerebbe il margine di sicurezza. Un mandato perso basterebbe a mettere in tensione tutto lo studio.',
        evidenceType: 'interpretation',
      },
    ],
    decision: 'Non firmare. Restiamo sette partner. Distribuiamo al masso il quaranta per cento degli utili e teniamo cassa per buyout interni, non per crescita imposta.',
    uncertaintyLevel: 'alto',
    uncertaintyExplanation: 'Due partner sono vicini al pensionamento. Se uscissero insieme, la cassa attuale potrebbe non bastare senza aiuto esterno.',
    mindChangingConditions: [
      'Due partner fondatori annunciano l’uscita nello stesso anno e il buyout interno supera cassa più un anno di utili.',
      'Il reddito medio dei partner scende per tre anni — soglia in cui un ingresso esterno da grande studio diventa razionale per chi resta.',
    ],
    verbatimQuotes: [
      {
        id: 'q-wf-eq-1',
        quote: 'Non è un obiettivo di crescita. È un debito di persone scritto nel contratto.',
        pageOrParagraph: 'PRT-X-2024-01, riunione partnership',
        speaker: 'Luca Ferrante',
      },
    ],
    interpretativeSummary: 'Hanno detto no a un assegno grande perché il prezzo era la libertà di decidere quanto crescere. Indipendenza qui significa anche rinunciare a capitali facili.',
    outcomeReviews: [
      {
        id: 'out-wf-eq-1',
        timeframe: '24_mesi',
        expectedOutcome: 'Nessuna quota ceduta a fondi; cassa sufficiente; eventuale buyout interno documentato.',
        actualOutcome: 'Nessuna cessione. Nel 2026 un principal ha comprato una piccola quota con finanziamento interno. Cassa solida a metà 2026.',
        status: 'verified_true',
        reviewDate: new Date('2026-09-01'),
      },
    ],
    createdAt: new Date('2024-09-05'),
    updatedAt: new Date('2026-09-01'),
  },
];
